### ISSUE TITLE
Task List for Merge

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/podsio-genesis#1]
Task list for getting the Genesis Child theme ready for Pods.io:
- [x] Add prism.js Code Syntax highlighting in functions.php (or plugin code)
- [x] Fix the header first: Needs Site Description, Logo, Social Menu, Download Pods, etc.
- [x] Primary Menu is actually FIXED (non-changeable). Might be easier to 'include' as a file at root theme and only apply ACTIVE page based on Child Theme.
- [x] Archive Templates for Video, Tutorials, Code Snippets, FAQs and the Landing Page
